### ISSUE TITLE
Error in trying to create grid

### ISSUE THREAD

**Issue by lukashanson400** [dpawlows/MGITM#1]
I've been using GITM for about a year now and have begun trying to use MGITM for further research. First time trying to run a standard version of the input file and the output file reports "Error in trying to create grid." I've never encountered this one with GITM, so I am not sure how to resolve this.
[output.pdf](https://github.com/user-attachments/files/17680197/output.pdf)
[UAM.pdf](https://github.com/user-attachments/files/17680198/UAM.pdf)

**Comment by lukashanson400** [comment]
That would be it. Didn't realize I copied the wrong job file into my run directory.

**Comment by aaronjridley** [comment]
Awesome! I will close this issue!
